#redis/.gitlab-ci.yml
stages:
  - build_and_deploy

build_and_deploy:
  stage: build_and_deploy
  image: docker:latest

  script:
    - cd ./deploymtents/

    - cp "$REDIS_ENV" .env
    - cp "$REDIS_ACL" .users.acl
    - cp "$REDIS_CONF" .redis.conf

    - apk add --no-cache bash
    - bash ./deploy.sh
  only:
    - main
  tags:
    - redis
