networks:
  redis_network:
    name: ${REDIS_NAME:-redis_server}_network

volumes:
  redis_data:
    name: ${REDIS_NAME:-redis_server}_data

services:
  redis_server:
    image: redis:8.4-alpine
    container_name: ${REDIS_NAME:-redis_server}
    ports:
      - "${REDIS_HOST_BIND_IP:-127.0.0.1}:${REDIS_EXTERNAL_PORT:-6379}:${REDIS_PORT:-6379}"
    volumes:
      - redis_data:/data
    networks:
      - redis_network
    restart: unless-stopped
    command: [
      "redis-server",
      "--bind", "0.0.0.0",
      "--port", "${REDIS_PORT:-6379}",
      "--appendonly", "yes",
      "--maxmemory", "${REDIS_MAXMEMORY:-256mb}",
      "--maxmemory-policy", "${REDIS_MAXMEMORY_POLICY:-allkeys-lru}",
      "--user", "default", "off", "-@all",
      "--user", "${REDIS_USERNAME}", "on", "${REDIS_PASSWORD_TYPE:->}${REDIS_PASSWORD}", "~*", "&*", "+@all"
    ]
