networks:
  redis_network:
    name: ${DOCKER_SHARED_NETWORK:-default_network}

services:
  redis_server:
    image: redis:alpine
    container_name: redis_server
    restart: unless-stopped
    networks:
      - redis_network
    ports:
      - "${REDIS_EXTERNAL_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
      - ./redis.conf:/etc/redis/redis.conf
      - ./users.acl:/etc/redis/users.acl
    command: [ "redis-server", "/etc/redis/redis.conf" ]

volumes:
  redis_data: